"""Still thumbnails for list rows, drawn by the original watch renderer.

python3 tools/animation/export_thumbs.py

Uses render.py unchanged (only its canvas size is enlarged), so list thumbnails
match the watch art exactly. The 3D viewer is used for detail and sessions.
"""
from pathlib import Path

try:
    from . import render
    from .export_3d import EXERCISES
    from .motions import pose_for
except ImportError:
    import render
    from export_3d import EXERCISES
    from motions import pose_for

ROOT = Path(__file__).resolve().parents[2]
# Phase showing each movement's most recognisable position.
PHASE = {'kb-pullover': .4, 'kb-press': .5, 'kb-clean': 0., 'kb-snatch': 0., 'kb-getup': .31, 'kb-halo': .25, 'kb-reverse-lunge': .25, 'kb-side-lunge': .25,
         'kb-side-bend': .25, 'kb-curl': .25}


def main():
    render.WIDTH, render.HEIGHT = 420, 234
    out = ROOT / 'assets/images/exercises'
    out.mkdir(parents=True, exist_ok=True)
    for exercise in EXERCISES:
        # Fit the camera to the whole loop, as the watch export does.
        poses = [pose_for(exercise, i / 48) for i in range(48)]
        camera = render.Camera(poses, poses[0]['view'])
        frame = render.draw_frame(pose_for(exercise, PHASE.get(exercise, .5)), camera)
        render.save_png(frame, out / f'{exercise}.png')
        print(exercise)
    lines = ['// Generated by tools/animation/export_thumbs.py. Do not edit.', '',
             'export const thumbnails: Record<string, number> = {']
    lines += [f"  '{e}': require('@/assets/images/exercises/{e}.png')," for e in EXERCISES]
    lines += ['};', '']
    (ROOT / 'src/animation/thumbnails.ts').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
