"""Export rig poses as 3D joint tracks for the app's live three.js character.

python3 tools/animation/export_3d.py

The same deterministic rig, motions and kettlebell choreography that produce the
watch PNGs are sampled densely and written as compact JSON. The app draws the
figure in 3D from these tracks, so the look follows render.py (tapered limbs,
shirt, pants, cuffs, shoes, head, bell) while the viewer can orbit freely.

Coordinates are converted from the rig (x forward, y left, z up) to three.js
(x = rig y, y = rig z, z = rig x); the mapping has determinant +1, so no mirror.
Values are stored in millimetres as integers.
"""
import argparse
import hashlib
import json
from pathlib import Path

try:
    from .motions import pose_for, DURATIONS, V2_MOTIONS
    from .validate import check_v2
except ImportError:
    from motions import pose_for, DURATIONS, V2_MOTIONS
    from validate import check_v2

ROOT = Path(__file__).resolve().parents[2]
PROFILES = json.loads((Path(__file__).parent / 'profiles.json').read_text())
CONTRACTS = json.loads((Path(__file__).parent / 'contracts.json').read_text())

EXERCISES = ['kb-swing', 'kb-deadlift', 'goblet-squat', 'kb-reverse-lunge',
             'kb-side-lunge', 'kb-upright-row', 'kb-bent-row', 'kb-side-bend',
             'kb-curl', 'kb-halo', 'kb-clean', 'kb-press', 'kb-snatch', 'kb-getup',
             'kb-pullover']
JOINTS = ['pelvis', 'chest', 'neck', 'head', 'face',
          *[f'{name}_{side}' for side in ('l', 'r')
            for name in ('hip', 'knee', 'ankle', 'heel', 'toe',
                         'shoulder', 'elbow', 'wrist', 'palm')]]
SAMPLE_FPS = 30


def to_three(point):
    x, y, z = point
    return [round(y * 1000), round(z * 1000), round(x * 1000)]


def export(exercise):
    profile = PROFILES[exercise]
    duration = DURATIONS[exercise]() if exercise in DURATIONS else profile['frames'] / profile['fps']
    samples = max(24, round(duration * SAMPLE_FPS))
    frames, errors, view = [], 0, None
    for index in range(samples):
        pose = pose_for(exercise, index / samples)
        errors += len(pose['qa']['ik_errors'])
        view = view or pose['view']
        joints = pose['joints']
        missing = [name for name in JOINTS if name not in joints]
        if missing:
            raise ValueError(f'{exercise}: missing joints {missing}')
        bells = []
        for prop in pose['props']:
            if prop['type'] != 'kettlebell':
                continue
            bells.append({'c': to_three(prop['center']),
                          'h': [to_three(p) for p in prop['handle']],
                          'r': round(prop.get('radius', .10) * 1000),
                          **({'horns': [to_three(h[0]) for h in prop['horns']]}
                             if 'horns' in prop else {}),
                          # Where each gripping hand holds this bell (the renderer wraps it there).
                          **({'g': {s: to_three(g) for s, g in prop['grips'].items()}}
                             if prop.get('grips') else {})})
        # Hand state per side, left then right: 0 free, 1 gripping a bell, 2 flat on the floor.
        gripping = {s for prop in pose['props'] for s in prop.get('grips', {})}
        hands = [1 if s in gripping else 2 if 'palm_' + s in pose['contacts'] else 0 for s in ('l', 'r')]
        frames.append({'j': [coord for name in JOINTS for coord in to_three(joints[name])],
                       'b': bells, 'hs': hands})
    if errors:
        raise ValueError(f'{exercise}: {errors} IK errors; fix the motion before export')
    if exercise in V2_MOTIONS:
        _, failures = check_v2(exercise)
        if failures:
            raise ValueError(f'{exercise}: validator v2 failed: {failures}')
    return {'id': exercise, 'duration': round(duration, 3), 'joints': JOINTS,
            'view': {'azimuth': view.get('azimuth', 65), 'elevation': view.get('elevation', 8),
                     **({'cropBelow': view['crop_below']} if 'crop_below' in view else {})},
            'contract': CONTRACTS.get(exercise), 'frames': frames}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', default=str(ROOT / 'assets/animations'))
    args = parser.parse_args()
    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    index = []
    for exercise in EXERCISES:
        clip = export(exercise)
        path = out / f'{exercise}.json'
        path.write_text(json.dumps(clip, separators=(',', ':')))
        index.append(exercise)
        print(f'{exercise}: {len(clip["frames"])} samples, {clip["duration"]}s, {path.stat().st_size // 1024} KB')
    # Static require() map for Metro, which cannot bundle dynamic JSON paths.
    lines = ['// Generated by tools/animation/export_3d.py. Do not edit.',
             "import type { Clip } from '@/animation/types';", '',
             'export const clips: Record<string, Clip> = {']
    lines += [f"  '{e}': require('@/assets/animations/{e}.json'),"for e in index]
    lines += ['};', '']
    (ROOT / 'src/animation/clips.ts').write_text('\n'.join(lines))
    # Revision identity for reviews: hash of every exported clip, in order.
    digest = hashlib.sha256()
    for exercise in index:
        digest.update((out / f'{exercise}.json').read_bytes())
    revision = digest.hexdigest()[:12]
    (ROOT / 'src/animation/revision.ts').write_text(
        '// Generated by tools/animation/export_3d.py. Do not edit.\n'
        f"export const ANIMATION_REVISION = '{revision}';\n")
    print('revision', revision)


if __name__ == '__main__':
    main()
