/**
 * Bodyweight exercises, and the few that need a chair, bar, doorframe, dumbbells or a band.
 * Names, counting and muscles follow tools/animation (spamset-catalog, contracts, muscles).
 * `harder` chains drive the variant suggestion once an exercise tops its range.
 */
import type { Exercise } from './exercises';

const bw = (e: Omit<Exercise, 'animation' | 'equipment'> & Partial<Pick<Exercise, 'equipment'>>): Exercise => ({
  animation: e.id,
  equipment: 'none',
  ...e,
});

export const BODYWEIGHT_EXERCISES: Exercise[] = [
  // Legs
  bw({
    id: 'squat',
    name: 'Squats',
    pattern: 'squat',
    unilateral: false,
    counting: 'One descent and stand',
    harder: 'reverse-lunge',
    primary: ['Quads', 'Glutes'],
    support: ['Core', 'Hamstrings'],
    cues: [
      'Feet about shoulder width, toes turned out slightly.',
      'Sit the hips back and down; knees track over the toes.',
      'Go as deep as you can with a long, neutral back.',
      'Drive through the whole foot to stand tall.',
    ],
  }),
  bw({
    id: 'reverse-lunge',
    name: 'Reverse lunges',
    pattern: 'lunge',
    unilateral: false,
    counting: 'One step back and return; alternate legs, each side counts',
    repSeconds: 3,
    primary: ['Quads', 'Glutes'],
    support: ['Core', 'Hamstrings'],
    cues: [
      'Step one foot back and lower the back knee toward the floor.',
      'Keep the torso upright and the front knee over the foot.',
      'Push through the front heel to return to standing.',
      'Switch legs every rep.',
    ],
  }),
  bw({
    id: 'calf-raise',
    name: 'Calf raises',
    pattern: 'squat',
    unilateral: false,
    counting: 'One rise onto the toes and lower',
    repSeconds: 2,
    primary: ['Calves'],
    support: [],
    cues: [
      'Stand tall, feet hip width; hold a wall for balance if needed.',
      'Rise as high as you can onto the balls of the feet.',
      'Pause at the top, then lower the heels slowly.',
    ],
  }),
  bw({
    id: 'glute-bridge',
    name: 'Glute bridges',
    pattern: 'hinge',
    unilateral: false,
    counting: 'One hip lift and lower',
    primary: ['Glutes'],
    support: ['Hamstrings', 'Core'],
    cues: [
      'Lie on your back, knees bent, feet flat and close to the hips.',
      'Squeeze the glutes and lift the hips into a straight line from knees to shoulders.',
      'Hold briefly at the top without arching the lower back.',
      'Lower with control.',
    ],
  }),
  bw({
    id: 'fly-steps',
    name: 'Fly steps',
    pattern: 'hinge',
    unilateral: false,
    counting: 'One hinge with a rear leg lift; alternate legs, each side counts',
    repSeconds: 4,
    primary: ['Glutes', 'Hamstrings'],
    support: ['Core', 'Upper back'],
    cues: [
      'Stand on one leg with a soft knee, arms out to the sides.',
      'Hinge forward as the free leg lifts straight behind you.',
      'Keep the hips square to the floor; body and back leg form one line.',
      'Return to standing and switch legs.',
    ],
  }),
  bw({
    id: 'side-leg-raises',
    name: 'Side leg raises',
    pattern: 'lunge',
    unilateral: false,
    counting: 'One raise and lower; alternate legs, each side counts',
    repSeconds: 2,
    primary: ['Glutes'],
    support: ['Core'],
    cues: [
      'Stand tall; hold a wall or chair for balance if needed.',
      'Lift one straight leg out to the side, toes pointing forward.',
      'Keep the torso upright; do not lean away.',
      'Lower with control and switch legs.',
    ],
  }),
  bw({
    id: 'standing-knee',
    name: 'Standing knee lifts',
    pattern: 'core',
    unilateral: false,
    counting: 'One knee lift and lower; alternate legs, each side counts',
    repSeconds: 1.5,
    primary: ['Hip flexors'],
    support: ['Core', 'Glutes'],
    cues: [
      'Stand tall with the arms relaxed.',
      'Lift one bent knee to hip height.',
      'Lower it and lift the other; keep the chest up.',
    ],
  }),
  bw({
    id: 'side-step',
    name: 'Side steps',
    pattern: 'lunge',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed; step out and together in both directions',
    primary: ['Glutes'],
    support: ['Quads', 'Calves'],
    cues: [
      'Stand in a slight squat, feet hip width.',
      'Step one foot out to the side and bring the other to meet it.',
      'Take a few steps one way, then come back.',
    ],
  }),

  // Push
  bw({
    id: 'wall-pushup',
    name: 'Wall push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One lean to the wall and press away',
    repSeconds: 2,
    harder: 'pushup',
    primary: ['Chest', 'Triceps'],
    support: ['Shoulders', 'Core'],
    cues: [
      'Hands on the wall at chest height, a little wider than the shoulders.',
      'Walk the feet back so the body leans in one straight line.',
      'Bend the elbows to bring the chest toward the wall.',
      'Press away until the arms are straight.',
    ],
  }),
  bw({
    id: 'pushup',
    name: 'Push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One descent and press',
    repSeconds: 2.5,
    harder: 'close-pushup',
    primary: ['Chest', 'Triceps'],
    support: ['Shoulders', 'Core'],
    cues: [
      'High plank: hands under the shoulders, body straight from head to heels.',
      'Lower the chest toward the floor, elbows about 45 degrees from the body.',
      'Keep the hips level; do not let them sag or pike.',
      'Press the floor away to straight arms.',
    ],
  }),
  bw({
    id: 'wide-pushup',
    name: 'Wide push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One descent and press',
    repSeconds: 2.5,
    harder: 'close-pushup',
    primary: ['Chest'],
    support: ['Shoulders', 'Triceps', 'Core'],
    cues: [
      'Hands wider than the shoulders, fingers forward.',
      'Lower the chest between the hands with a straight body.',
      'Press back up without locking out hard.',
    ],
  }),
  bw({
    id: 'close-pushup',
    name: 'Close-grip push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One descent and press',
    repSeconds: 2.5,
    harder: 'power-pushup',
    primary: ['Triceps', 'Chest'],
    support: ['Shoulders', 'Core'],
    cues: [
      'Hands under the chest, close together.',
      'Lower with the elbows brushing the sides of the body.',
      'Press up to straight arms; the body stays rigid.',
    ],
  }),
  bw({
    id: 'staggered-pushup',
    name: 'Staggered push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One descent and press; swap the hands between sets',
    repSeconds: 2.5,
    harder: 'stacked-pushup',
    primary: ['Chest', 'Triceps'],
    support: ['Shoulders', 'Core'],
    cues: [
      'One hand forward of the shoulder, the other back by the ribs.',
      'Lower evenly; keep the hips square to the floor.',
      'Press up, and swap the hand positions next set.',
    ],
  }),
  bw({
    id: 'stacked-pushup',
    name: 'Stacked-feet push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One descent and press',
    repSeconds: 2.5,
    harder: 'raised-leg-pushup',
    primary: ['Chest', 'Triceps'],
    support: ['Obliques', 'Shoulders'],
    cues: [
      'From a high plank, rest one foot on top of the other.',
      'Brace hard so the hips do not twist.',
      'Lower and press as in a normal push-up.',
    ],
  }),
  bw({
    id: 'raised-leg-pushup',
    name: 'Raised-leg push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One push-up with one leg lifted; alternate legs',
    repSeconds: 3,
    harder: 'spiderman-pushup',
    primary: ['Chest', 'Triceps'],
    support: ['Glutes', 'Core'],
    cues: [
      'High plank, then lift one straight leg off the floor.',
      'Lower and press while the leg stays up and the hips stay level.',
      'Put the leg down and lift the other for the next rep.',
    ],
  }),
  bw({
    id: 'spiderman-pushup',
    name: 'Spiderman push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One push-up with a knee drive; alternate sides',
    repSeconds: 3,
    primary: ['Chest', 'Triceps'],
    support: ['Obliques', 'Hip flexors'],
    cues: [
      'As you lower, draw one knee out to the side toward the same elbow.',
      'Keep the hips low and the body long.',
      'Press up as the leg returns; switch sides each rep.',
    ],
  }),
  bw({
    id: 'power-pushup',
    name: 'Power push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One explosive press and soft landing',
    repSeconds: 3,
    harder: 'clapping-pushup',
    primary: ['Chest', 'Triceps'],
    support: ['Shoulders', 'Core'],
    cues: [
      'Lower under control into the bottom of a push-up.',
      'Press so hard the hands leave the floor.',
      'Land with soft elbows and go straight into the next rep.',
    ],
  }),
  bw({
    id: 'clapping-pushup',
    name: 'Clapping push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One explosive press, clap and landing',
    repSeconds: 3,
    primary: ['Chest', 'Triceps'],
    support: ['Shoulders', 'Core'],
    cues: [
      'Lower under control, then explode up.',
      'Clap quickly in the air and get the hands back under the shoulders.',
      'Land with soft elbows and a rigid body; reset before the next rep.',
    ],
  }),
  bw({
    id: 'pike-pushup',
    name: 'Pike push-ups',
    pattern: 'press',
    unilateral: false,
    counting: 'One lowering of the head toward the floor and press',
    repSeconds: 3,
    primary: ['Shoulders', 'Triceps'],
    support: ['Upper back', 'Core'],
    cues: [
      'Hips high in an inverted V, hands shoulder width.',
      'Bend the elbows to bring the top of the head toward the floor.',
      'Press back up through the shoulders; hips stay high.',
    ],
  }),
  bw({
    id: 'pseudo-planche',
    name: 'Pseudo planche',
    pattern: 'press',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed lean and hold',
    primary: ['Shoulders', 'Chest'],
    support: ['Core', 'Biceps', 'Forearms'],
    cues: [
      'High plank with the fingers turned out or back.',
      'Lean the shoulders forward past the hands on straight arms.',
      'Hold with the body rigid; lean less if the wrists complain.',
    ],
  }),
  bw({
    id: 'tricep-dips',
    name: 'Tricep dips',
    pattern: 'arms',
    unilateral: false,
    counting: 'One lower and press',
    harder: 'tricep-extensions',
    primary: ['Triceps'],
    support: ['Chest', 'Shoulders'],
    cues: [
      'Sit on the floor, hands behind the hips, fingers toward you; lift the hips.',
      'Bend the elbows straight back to lower the hips.',
      'Press back up to straight arms.',
    ],
  }),
  bw({
    id: 'tricep-extensions',
    name: 'Tricep extensions',
    pattern: 'arms',
    unilateral: false,
    counting: 'One press from the forearms to the hands and lower',
    repSeconds: 3,
    primary: ['Triceps'],
    support: ['Core', 'Shoulders'],
    cues: [
      'Forearm plank with the hands flat and shoulder width.',
      'Press through the palms to straighten the arms, keeping the elbows in.',
      'Lower back onto the forearms with control.',
    ],
  }),

  // Core
  bw({
    id: 'plank',
    name: 'Forearm plank',
    pattern: 'core',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed hold',
    harder: 'shoulder-taps',
    primary: ['Core'],
    support: ['Obliques', 'Shoulders'],
    cues: [
      'Elbows under the shoulders, forearms flat.',
      'Straight line from head to heels: squeeze the glutes, ribs down.',
      'Breathe steadily; stop when the hips start to sag.',
    ],
  }),
  bw({
    id: 'shoulder-taps',
    name: 'Shoulder taps',
    pattern: 'core',
    unilateral: false,
    counting: 'One tap and replace; alternate hands, each side counts',
    repSeconds: 1.5,
    harder: 'alt-arm-leg-plank',
    primary: ['Core'],
    support: ['Obliques', 'Shoulders'],
    cues: [
      'High plank with the feet a little wider than the hips.',
      'Lift one hand to tap the opposite shoulder.',
      'Keep the hips still; do not rock side to side.',
    ],
  }),
  bw({
    id: 'alt-arm-leg-plank',
    name: 'Arm and leg plank',
    pattern: 'core',
    unilateral: false,
    counting: 'One reach of an opposite arm and leg; alternate sides',
    repSeconds: 4,
    primary: ['Core'],
    support: ['Glutes', 'Shoulders'],
    cues: [
      'High plank, feet wide for balance.',
      'Reach one arm forward and the opposite leg back at the same time.',
      'Hold for a breath with the hips level, then switch.',
    ],
  }),
  bw({
    id: 'bird-dog',
    name: 'Bird dogs',
    pattern: 'core',
    unilateral: false,
    counting: 'One reach of an opposite arm and leg; alternate sides',
    repSeconds: 4,
    harder: 'alt-arm-leg-plank',
    primary: ['Core'],
    support: ['Obliques', 'Glutes', 'Shoulders'],
    cues: [
      'Hands under the shoulders, knees under the hips.',
      'Reach one arm forward and the opposite leg back until both are level.',
      'Keep the back flat and the hips square, then switch sides.',
    ],
  }),
  bw({
    id: 'sit-ups',
    name: 'Sit-ups',
    pattern: 'core',
    unilateral: false,
    counting: 'One curl up and lower',
    primary: ['Core'],
    support: ['Hip flexors'],
    cues: [
      'Lie with the knees bent, feet flat, hands lightly behind the head.',
      'Curl up one vertebra at a time without pulling on the neck.',
      'Lower slowly back to the floor.',
    ],
  }),
  bw({
    id: 'reverse-crunches',
    name: 'Reverse crunches',
    pattern: 'core',
    unilateral: false,
    counting: 'One curl of the knees in and lower',
    harder: 'leg-raises',
    primary: ['Core'],
    support: ['Hip flexors'],
    cues: [
      'Lie on your back, knees bent at 90 degrees above the hips.',
      'Curl the knees toward the chest so the hips lift off the floor.',
      'Lower slowly without letting the feet drop.',
    ],
  }),
  bw({
    id: 'bicycle-crunches',
    name: 'Bicycle crunches',
    pattern: 'core',
    unilateral: false,
    counting: 'One elbow-to-knee twist; alternate sides, each side counts',
    repSeconds: 1.5,
    primary: ['Obliques', 'Core'],
    support: ['Hip flexors'],
    cues: [
      'Shoulders off the floor, hands lightly behind the head.',
      'Bring one knee in as the opposite elbow turns toward it; extend the other leg.',
      'Switch sides in a smooth pedalling rhythm.',
    ],
  }),
  bw({
    id: 'flutter-kicks',
    name: 'Flutter kicks',
    pattern: 'core',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed',
    primary: ['Core'],
    support: ['Hip flexors'],
    cues: [
      'Lie on your back, legs straight and just off the floor.',
      'Press the lower back into the floor.',
      'Kick the legs up and down in small, quick alternating movements.',
    ],
  }),
  bw({
    id: 'leg-raises',
    name: 'Leg raises',
    pattern: 'core',
    unilateral: false,
    counting: 'One raise and lower',
    primary: ['Core'],
    support: ['Hip flexors'],
    cues: [
      'Lie on your back with straight legs hovering above the floor.',
      'Raise the legs together to about 45 degrees.',
      'Lower slowly; keep the lower back pressed down.',
    ],
  }),
  bw({
    id: 'superman',
    name: 'Superman',
    pattern: 'core',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed lift and hold',
    primary: ['Lower back', 'Glutes'],
    support: ['Upper back', 'Hamstrings'],
    cues: [
      'Lie face down, arms reaching forward.',
      'Lift the arms, chest and legs a few centimetres off the floor.',
      'Hold with the neck long, eyes on the floor.',
    ],
  }),
  bw({
    id: 'back-lifts',
    name: 'Back lifts',
    pattern: 'core',
    unilateral: false,
    counting: 'One chest lift and lower',
    harder: 'superman',
    primary: ['Lower back'],
    support: ['Glutes', 'Upper back'],
    cues: [
      'Lie face down, fingertips at the temples.',
      'Lift the chest off the floor; the feet stay down.',
      'Lower with control, neck in line with the spine.',
    ],
  }),

  // Full body and conditioning
  bw({
    id: 'climbers',
    name: 'Climbers',
    pattern: 'full-body',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed',
    primary: ['Core', 'Hip flexors'],
    support: ['Shoulders', 'Quads'],
    cues: [
      'High plank, hands under the shoulders.',
      'Drive one knee toward the chest, then switch legs quickly.',
      'Keep the hips low and the shoulders over the hands.',
    ],
  }),
  bw({
    id: 'plank-jump-ins',
    name: 'Plank jump-ins',
    pattern: 'full-body',
    unilateral: false,
    counting: 'One jump in and out',
    repSeconds: 2,
    primary: ['Core', 'Quads'],
    support: ['Shoulders', 'Hip flexors'],
    cues: [
      'Start in a high plank.',
      'Jump both feet in toward the hands into a crouch.',
      'Jump them back out to the plank; land softly.',
    ],
  }),
  bw({
    id: 'punches',
    name: 'Punches',
    pattern: 'full-body',
    unilateral: false,
    counting: 'Each punch counts',
    repSeconds: 1,
    primary: ['Shoulders', 'Core'],
    support: ['Chest', 'Triceps'],
    cues: [
      'Fighting stance: feet staggered, fists up by the chin.',
      'Jab with the lead hand, then cross with the rear hand as the hips turn.',
      'Snap each fist straight back to the guard.',
    ],
  }),
  bw({
    id: 'side-to-side-chops',
    name: 'Side-to-side chops',
    pattern: 'core',
    unilateral: false,
    counting: 'Each swing counts',
    repSeconds: 1.5,
    primary: ['Obliques'],
    support: ['Shoulders', 'Core'],
    cues: [
      'Stand with the feet wide and the hands clasped.',
      'Swing the hands across the body from one side to the other.',
      'Turn through the torso and pivot the back foot with each swing.',
    ],
  }),
  bw({
    id: 'chest-expansions',
    name: 'Chest expansions',
    pattern: 'pull',
    unilateral: false,
    counting: 'Each open and cross counts',
    repSeconds: 1.5,
    primary: ['Upper back', 'Chest'],
    support: ['Shoulders'],
    cues: [
      'Stand tall with the arms out in front at shoulder height.',
      'Open the arms wide, squeezing the shoulder blades together.',
      'Swing them back in to cross in front, alternating which arm is on top.',
    ],
  }),

  // Chair
  bw({
    id: 'sit-stand',
    name: 'Sit-to-stands',
    pattern: 'squat',
    equipment: 'chair',
    unilateral: false,
    counting: 'One rise to standing and controlled sit',
    harder: 'squat',
    primary: ['Quads', 'Glutes'],
    support: ['Core'],
    cues: [
      'Sit near the front of a sturdy chair, feet flat and hip width.',
      'Lean the chest forward and stand up without using your hands.',
      'Sit back down slowly and with control.',
    ],
  }),
  bw({
    id: 'seated-knee',
    name: 'Seated knee lifts',
    pattern: 'core',
    equipment: 'chair',
    unilateral: false,
    counting: 'One knee lift and lower; alternate legs, each side counts',
    repSeconds: 1.5,
    harder: 'standing-knee',
    primary: ['Hip flexors'],
    support: ['Core'],
    cues: [
      'Sit tall near the front of the chair, hands on the sides of the seat.',
      'Lift one bent knee toward the chest.',
      'Lower it and lift the other; keep the back upright.',
    ],
  }),
  bw({
    id: 'decline-pushup',
    name: 'Decline push-ups',
    pattern: 'press',
    equipment: 'chair',
    unilateral: false,
    counting: 'One descent and press',
    repSeconds: 2.5,
    harder: 'pike-pushup',
    primary: ['Chest', 'Shoulders'],
    support: ['Triceps', 'Core'],
    cues: [
      'Feet on the chair seat, hands on the floor under the shoulders.',
      'Lower the chest toward the floor with a straight body.',
      'Press back up; do not let the hips sag.',
    ],
  }),

  // Bar, doorframe, dumbbells, band
  bw({
    id: 'chin-ups',
    name: 'Chin-ups',
    pattern: 'pull',
    equipment: 'pullup-bar',
    unilateral: false,
    counting: 'One pull and lower',
    repSeconds: 3.5,
    harder: 'pull-ups',
    primary: ['Lats', 'Biceps'],
    support: ['Upper back', 'Core', 'Grip'],
    cues: [
      'Hang with the palms facing you, hands shoulder width.',
      'Pull the shoulders down, then pull until the chin clears the bar.',
      'Lower all the way to straight arms under control.',
    ],
  }),
  bw({
    id: 'pull-ups',
    name: 'Pull-ups',
    pattern: 'pull',
    equipment: 'pullup-bar',
    unilateral: false,
    counting: 'One pull and lower',
    repSeconds: 3.5,
    primary: ['Lats', 'Upper back'],
    support: ['Biceps', 'Core', 'Grip'],
    cues: [
      'Hang with the palms facing away, hands a little wider than the shoulders.',
      'Drive the elbows down to pull the chin over the bar.',
      'Lower to straight arms without swinging.',
    ],
  }),
  bw({
    id: 'doorframe-rows',
    name: 'Doorframe rows',
    pattern: 'pull',
    equipment: 'doorframe',
    unilateral: false,
    counting: 'One pull in and lower',
    harder: 'chin-ups',
    primary: ['Upper back', 'Biceps'],
    support: ['Lats', 'Grip'],
    cues: [
      'Hold both sides of a sturdy doorframe, feet close to the threshold.',
      'Lean back on straight arms with the body in one line.',
      'Pull the chest toward the frame, then lower slowly. Walk the feet closer to make it harder.',
    ],
  }),
  bw({
    id: 'db-curl',
    name: 'Dumbbell curls',
    pattern: 'arms',
    equipment: 'dumbbells',
    unilateral: false,
    counting: 'One curl and lower with both arms',
    primary: ['Biceps'],
    support: ['Forearms'],
    cues: [
      'Stand tall with a dumbbell in each hand, palms forward.',
      'Curl the weights up with the upper arms fixed at your sides.',
      'Lower slowly to straight arms.',
    ],
  }),
  bw({
    id: 'band-pull',
    name: 'Band pull-aparts',
    pattern: 'pull',
    equipment: 'band',
    unilateral: false,
    counting: 'One opening and return',
    repSeconds: 2,
    primary: ['Upper back', 'Rear shoulders'],
    support: ['Traps'],
    cues: [
      'Hold the band at chest height, arms straight and hands shoulder width.',
      'Pull the band apart until it touches the chest, squeezing the shoulder blades.',
      'Return slowly under tension.',
    ],
  }),
];
