/**
 * Stretches and mobility drills. They are timed or counted like any exercise but never
 * progress: stretch to mild tension, breathe, never bounce.
 */
import type { Exercise } from './exercises';

const stretch = (e: Omit<Exercise, 'animation' | 'equipment' | 'kind' | 'pattern'>): Exercise => ({
  animation: e.id,
  equipment: 'none',
  kind: 'stretch',
  pattern: 'mobility',
  ...e,
});

export const STRETCHES: Exercise[] = [
  stretch({
    id: 'shoulder-circle',
    name: 'Shoulder circles',
    unilateral: false,
    counting: 'One full circle backward',
    repSeconds: 2,
    primary: ['Traps'],
    support: ['Upper back'],
    cues: [
      'Stand tall with the arms relaxed.',
      'Roll the shoulders forward, up, back and down in a big circle.',
      'Move slowly and keep the neck long.',
    ],
  }),
  stretch({
    id: 'neck-flexion',
    name: 'Neck flexion',
    unilateral: false,
    counting: 'One lower, hold and lift',
    repSeconds: 6,
    primary: ['Neck'],
    support: ['Upper back'],
    cues: [
      'Stand or sit tall, shoulders relaxed.',
      'Lower the chin toward the chest until you feel the back of the neck.',
      'Hold for a breath or two, then lift slowly.',
    ],
  }),
  stretch({
    id: 'neck-extension',
    name: 'Neck extension',
    unilateral: false,
    counting: 'One look up, hold and return',
    repSeconds: 6,
    primary: ['Neck'],
    support: [],
    cues: [
      'Stand or sit tall.',
      'Look up gently, letting the head tilt back without crunching the neck.',
      'Hold briefly and return to neutral.',
    ],
  }),
  stretch({
    id: 'side-neck',
    name: 'Side neck stretch',
    unilateral: false,
    counting: 'One tilt, hold and return; alternate sides',
    repSeconds: 8,
    primary: ['Neck'],
    support: ['Traps'],
    cues: [
      'Shoulders down and relaxed.',
      'Tilt one ear toward the shoulder without lifting the shoulder.',
      'Hold, return to the middle and switch sides.',
    ],
  }),
  stretch({
    id: 'overhead-reach',
    name: 'Overhead reach',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed hold',
    primary: ['Lats', 'Shoulders'],
    support: ['Core'],
    cues: [
      'Interlace the fingers and press the palms up overhead.',
      'Reach tall with the arms beside the ears.',
      'Keep the ribs down; breathe into the stretch.',
    ],
  }),
  stretch({
    id: 'behind-back-clasp',
    name: 'Behind-back clasp',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed hold',
    primary: ['Chest', 'Shoulders'],
    support: ['Biceps'],
    cues: [
      'Clasp the hands behind the back.',
      'Straighten the arms and lift them away from the body.',
      'Open the chest and keep the chin level.',
    ],
  }),
  stretch({
    id: 'torso-extension',
    name: 'Standing back bends',
    unilateral: false,
    counting: 'One lean back and return',
    repSeconds: 4,
    primary: ['Core', 'Hip flexors'],
    support: ['Lower back'],
    cues: [
      'Hands on the hips, feet hip width.',
      'Push the hips forward and lean back gently.',
      'Return upright without holding at the end.',
    ],
  }),
  stretch({
    id: 'side-bend',
    name: 'Side bends',
    unilateral: false,
    counting: 'One bend and return; alternate sides',
    repSeconds: 4,
    primary: ['Obliques', 'Lats'],
    support: [],
    cues: [
      'Reach one arm overhead.',
      'Bend sideways over the opposite hip, reaching long.',
      'Return upright and switch sides.',
    ],
  }),
  stretch({
    id: 'oblique-twist',
    name: 'Standing twists',
    unilateral: false,
    counting: 'One turn and return; alternate sides',
    repSeconds: 3,
    primary: ['Obliques'],
    support: ['Upper back'],
    cues: [
      'Hands clasped at chest height, elbows out.',
      'Turn the upper body to one side; the hips stay facing forward.',
      'Return to the middle and turn the other way.',
    ],
  }),
  stretch({
    id: 'cat-cow',
    name: 'Cat-cow',
    unilateral: false,
    counting: 'One cat and one cow',
    repSeconds: 6,
    primary: ['Back'],
    support: ['Core', 'Neck'],
    cues: [
      'Hands under the shoulders, knees under the hips.',
      'Round the back toward the ceiling and drop the head (cat).',
      'Let the belly sink and lift the head and tailbone (cow).',
      'Move slowly with the breath.',
    ],
  }),
  stretch({
    id: 'quad-stretch',
    name: 'Standing quad stretch',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed hold; switch legs halfway',
    primary: ['Quads'],
    support: ['Hip flexors'],
    cues: [
      'Stand on one leg; hold a wall if needed.',
      'Bend the other knee and hold the ankle behind you.',
      'Knees together, hips pushed slightly forward. Switch legs halfway.',
    ],
  }),
  stretch({
    id: 'hamstring-stretch',
    name: 'Hamstring stretch',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed hold; switch legs halfway',
    primary: ['Hamstrings'],
    support: ['Calves'],
    cues: [
      'Step one heel forward, toes up, the back knee soft.',
      'Hinge forward from the hips with a long back.',
      'Stop at a mild pull behind the thigh. Switch legs halfway.',
    ],
  }),
  stretch({
    id: 'hip-flexor-lunge',
    name: 'Hip-flexor stretch',
    unit: 'seconds',
    unilateral: false,
    counting: 'Timed hold; switch legs halfway',
    primary: ['Hip flexors'],
    support: ['Quads'],
    cues: [
      'Half-kneel with the front knee over the ankle.',
      'Squeeze the back glute and shift the hips gently forward.',
      'Stay tall through the chest. Switch legs halfway.',
    ],
  }),
  stretch({
    id: 'reclined-twist',
    name: 'Knee rolls',
    unilateral: false,
    counting: 'One roll to a side and back; alternate sides',
    repSeconds: 5,
    primary: ['Lower back', 'Obliques'],
    support: ['Glutes'],
    cues: [
      'Lie on your back, knees bent and together, arms out wide.',
      'Let both knees roll slowly to one side; shoulders stay down.',
      'Bring them back through the middle and roll the other way.',
    ],
  }),
];
