// Generated by tools/animation/export_3d.py. Do not edit.
import type { Clip } from '@/animation/types';

export const clips: Record<string, Clip> = {
  'kb-swing': require('@/assets/animations/kb-swing.json'),
  'kb-deadlift': require('@/assets/animations/kb-deadlift.json'),
  'goblet-squat': require('@/assets/animations/goblet-squat.json'),
  'kb-reverse-lunge': require('@/assets/animations/kb-reverse-lunge.json'),
  'kb-side-lunge': require('@/assets/animations/kb-side-lunge.json'),
  'kb-upright-row': require('@/assets/animations/kb-upright-row.json'),
  'kb-bent-row': require('@/assets/animations/kb-bent-row.json'),
  'kb-side-bend': require('@/assets/animations/kb-side-bend.json'),
  'kb-curl': require('@/assets/animations/kb-curl.json'),
  'kb-halo': require('@/assets/animations/kb-halo.json'),
  'kb-clean': require('@/assets/animations/kb-clean.json'),
  'kb-press': require('@/assets/animations/kb-press.json'),
  'kb-snatch': require('@/assets/animations/kb-snatch.json'),
  'kb-getup': require('@/assets/animations/kb-getup.json'),
  'kb-pullover': require('@/assets/animations/kb-pullover.json'),
};
