// Generated by tools/animation/export_3d.py. Do not edit.
export type ReviewEntry = { id: string; name: string; group: string };
export const REVIEW_CATALOG: ReviewEntry[] = [
  {
    "id": "kb-swing",
    "name": "Kettlebell swings",
    "group": "kettlebell"
  },
  {
    "id": "kb-deadlift",
    "name": "Kettlebell deadlift",
    "group": "kettlebell"
  },
  {
    "id": "goblet-squat",
    "name": "Goblet squats",
    "group": "kettlebell"
  },
  {
    "id": "kb-reverse-lunge",
    "name": "Goblet reverse lunges",
    "group": "kettlebell"
  },
  {
    "id": "kb-side-lunge",
    "name": "Goblet side lunges",
    "group": "kettlebell"
  },
  {
    "id": "kb-upright-row",
    "name": "Kettlebell upright rows",
    "group": "kettlebell"
  },
  {
    "id": "kb-bent-row",
    "name": "Kettlebell bent rows",
    "group": "kettlebell"
  },
  {
    "id": "kb-side-bend",
    "name": "Kettlebell side bends",
    "group": "kettlebell"
  },
  {
    "id": "kb-curl",
    "name": "Kettlebell curls",
    "group": "kettlebell"
  },
  {
    "id": "kb-halo",
    "name": "Kettlebell halos",
    "group": "kettlebell"
  },
  {
    "id": "kb-clean",
    "name": "kb-clean",
    "group": "kettlebell"
  },
  {
    "id": "kb-press",
    "name": "kb-press",
    "group": "kettlebell"
  },
  {
    "id": "kb-snatch",
    "name": "kb-snatch",
    "group": "kettlebell"
  },
  {
    "id": "kb-getup",
    "name": "kb-getup",
    "group": "kettlebell"
  },
  {
    "id": "kb-pullover",
    "name": "kb-pullover",
    "group": "kettlebell"
  },
  {
    "id": "squat",
    "name": "Squats",
    "group": "bodyweight"
  },
  {
    "id": "wall-pushup",
    "name": "Wall push-ups",
    "group": "bodyweight"
  },
  {
    "id": "calf-raise",
    "name": "Calf raises",
    "group": "bodyweight"
  },
  {
    "id": "shoulder-circle",
    "name": "Shoulder circles",
    "group": "stretching"
  },
  {
    "id": "reverse-lunge",
    "name": "Reverse lunges",
    "group": "bodyweight"
  },
  {
    "id": "pushup",
    "name": "Push-ups",
    "group": "bodyweight"
  },
  {
    "id": "wide-pushup",
    "name": "Wide push-ups",
    "group": "bodyweight"
  },
  {
    "id": "close-pushup",
    "name": "Close-grip push-ups",
    "group": "bodyweight"
  },
  {
    "id": "staggered-pushup",
    "name": "Staggered push-ups",
    "group": "bodyweight"
  },
  {
    "id": "stacked-pushup",
    "name": "Stacked-feet push-ups",
    "group": "bodyweight"
  },
  {
    "id": "raised-leg-pushup",
    "name": "Raised-leg push-ups",
    "group": "bodyweight"
  },
  {
    "id": "spiderman-pushup",
    "name": "Spiderman push-ups",
    "group": "bodyweight"
  },
  {
    "id": "decline-pushup",
    "name": "Decline push-ups",
    "group": "chair"
  },
  {
    "id": "clapping-pushup",
    "name": "Clapping push-ups",
    "group": "bodyweight"
  },
  {
    "id": "power-pushup",
    "name": "Power push-ups",
    "group": "bodyweight"
  },
  {
    "id": "pike-pushup",
    "name": "Pike push-ups",
    "group": "bodyweight"
  },
  {
    "id": "standing-knee",
    "name": "Standing knee lifts",
    "group": "bodyweight"
  },
  {
    "id": "side-step",
    "name": "Side steps",
    "group": "bodyweight"
  },
  {
    "id": "glute-bridge",
    "name": "Glute bridges",
    "group": "bodyweight"
  },
  {
    "id": "bird-dog",
    "name": "Bird dogs",
    "group": "bodyweight"
  },
  {
    "id": "plank",
    "name": "Forearm plank",
    "group": "bodyweight"
  },
  {
    "id": "sit-ups",
    "name": "Sit-ups",
    "group": "bodyweight"
  },
  {
    "id": "reverse-crunches",
    "name": "Reverse crunches",
    "group": "bodyweight"
  },
  {
    "id": "bicycle-crunches",
    "name": "Bicycle crunches",
    "group": "bodyweight"
  },
  {
    "id": "flutter-kicks",
    "name": "Flutter kicks",
    "group": "bodyweight"
  },
  {
    "id": "leg-raises",
    "name": "Leg raises",
    "group": "bodyweight"
  },
  {
    "id": "superman",
    "name": "Superman",
    "group": "bodyweight"
  },
  {
    "id": "back-lifts",
    "name": "Back lifts",
    "group": "bodyweight"
  },
  {
    "id": "alt-arm-leg-plank",
    "name": "Arm and leg plank",
    "group": "bodyweight"
  },
  {
    "id": "shoulder-taps",
    "name": "Shoulder taps",
    "group": "bodyweight"
  },
  {
    "id": "climbers",
    "name": "Climbers",
    "group": "bodyweight"
  },
  {
    "id": "plank-jump-ins",
    "name": "Plank jump-ins",
    "group": "bodyweight"
  },
  {
    "id": "tricep-extensions",
    "name": "Tricep extensions",
    "group": "bodyweight"
  },
  {
    "id": "pseudo-planche",
    "name": "Pseudo planche",
    "group": "bodyweight"
  },
  {
    "id": "tricep-dips",
    "name": "Tricep dips",
    "group": "bodyweight"
  },
  {
    "id": "fly-steps",
    "name": "Fly steps",
    "group": "bodyweight"
  },
  {
    "id": "side-leg-raises",
    "name": "Side leg raises",
    "group": "bodyweight"
  },
  {
    "id": "punches",
    "name": "Punches",
    "group": "bodyweight"
  },
  {
    "id": "side-to-side-chops",
    "name": "Side-to-side chops",
    "group": "bodyweight"
  },
  {
    "id": "chest-expansions",
    "name": "Chest expansions",
    "group": "bodyweight"
  },
  {
    "id": "chin-ups",
    "name": "Chin-ups",
    "group": "pullup-bar"
  },
  {
    "id": "pull-ups",
    "name": "Pull-ups",
    "group": "pullup-bar"
  },
  {
    "id": "doorframe-rows",
    "name": "Doorframe rows",
    "group": "doorframe"
  },
  {
    "id": "sit-stand",
    "name": "Sit-to-stands",
    "group": "chair"
  },
  {
    "id": "seated-knee",
    "name": "Seated knee lifts",
    "group": "chair"
  },
  {
    "id": "db-curl",
    "name": "Dumbbell curls",
    "group": "dumbbells"
  },
  {
    "id": "band-pull",
    "name": "Band pull-aparts",
    "group": "band"
  },
  {
    "id": "neck-flexion",
    "name": "Neck flexion",
    "group": "stretching"
  },
  {
    "id": "neck-extension",
    "name": "Neck extension",
    "group": "stretching"
  },
  {
    "id": "side-neck",
    "name": "Side neck stretch",
    "group": "stretching"
  },
  {
    "id": "overhead-reach",
    "name": "Overhead reach",
    "group": "stretching"
  },
  {
    "id": "behind-back-clasp",
    "name": "Behind-back clasp",
    "group": "stretching"
  },
  {
    "id": "torso-extension",
    "name": "Standing back bends",
    "group": "stretching"
  },
  {
    "id": "side-bend",
    "name": "Side bends",
    "group": "stretching"
  },
  {
    "id": "oblique-twist",
    "name": "Standing twists",
    "group": "stretching"
  },
  {
    "id": "cat-cow",
    "name": "Cat-cow",
    "group": "stretching"
  },
  {
    "id": "quad-stretch",
    "name": "Standing quad stretch",
    "group": "stretching"
  },
  {
    "id": "hamstring-stretch",
    "name": "Hamstring stretch",
    "group": "stretching"
  },
  {
    "id": "hip-flexor-lunge",
    "name": "Hip-flexor stretch",
    "group": "stretching"
  },
  {
    "id": "reclined-twist",
    "name": "Knee rolls",
    "group": "stretching"
  },
  {
    "id": "gear-crouch",
    "name": "Gear crouch",
    "group": "celebration"
  },
  {
    "id": "heart-salute",
    "name": "Heart salute",
    "group": "celebration"
  }
];
