// Generated by tools/animation/export_thumbs.py. Do not edit.

export const thumbnails: Record<string, number> = {
  'kb-swing': require('@/assets/images/exercises/kb-swing.png'),
  'kb-deadlift': require('@/assets/images/exercises/kb-deadlift.png'),
  'goblet-squat': require('@/assets/images/exercises/goblet-squat.png'),
  'kb-reverse-lunge': require('@/assets/images/exercises/kb-reverse-lunge.png'),
  'kb-side-lunge': require('@/assets/images/exercises/kb-side-lunge.png'),
  'kb-upright-row': require('@/assets/images/exercises/kb-upright-row.png'),
  'kb-bent-row': require('@/assets/images/exercises/kb-bent-row.png'),
  'kb-side-bend': require('@/assets/images/exercises/kb-side-bend.png'),
  'kb-curl': require('@/assets/images/exercises/kb-curl.png'),
  'kb-halo': require('@/assets/images/exercises/kb-halo.png'),
  'kb-clean': require('@/assets/images/exercises/kb-clean.png'),
  'kb-press': require('@/assets/images/exercises/kb-press.png'),
  'kb-snatch': require('@/assets/images/exercises/kb-snatch.png'),
  'kb-getup': require('@/assets/images/exercises/kb-getup.png'),
  'kb-pullover': require('@/assets/images/exercises/kb-pullover.png'),
};
